import { promises as fs } from "node:fs";
import * as path from "node:path";
import pc from "picocolors";
import { findProjectConfig } from "../storage/project-config.js";
import { readDirectoryFiles } from "../utils/files.js";
import { logger } from "../ui/logger.js";
import { createTable } from "../ui/table.js";
import { Push44Error } from "../utils/errors.js";

const ENV_VAR_REGEX = /(?:import\.meta\.env\.|process\.env\.)([A-Z0-9_]+)/g;

export async function envSyncCommand(options: { generateExample?: boolean } = {}): Promise<void> {
  const found = await findProjectConfig();
  if (!found) {
    throw new Push44Error("No .push44.json project config found in current directory.");
  }

  const { projectRoot } = found;
  const files = await readDirectoryFiles(projectRoot);

  const discoveredVars = new Set<string>();

  for (const file of files) {
    if (file.binary || file.path.includes(".env")) continue;
    let match;
    while ((match = ENV_VAR_REGEX.exec(file.content)) !== null) {
      const varName = match[1];
      if (varName !== "NODE_ENV" && varName !== "BASE_URL" && varName !== "MODE") {
        discoveredVars.add(varName);
      }
    }
  }

  const varList = Array.from(discoveredVars).sort();

  if (varList.length === 0) {
    logger.info("No custom environment variables detected in project source files.");
    return;
  }

  // Check local .env / .env.local
  const envLocalPath = path.join(projectRoot, ".env.local");
  const envPath = path.join(projectRoot, ".env");

  let localContent = "";
  try {
    if (await fileExists(envLocalPath)) localContent = await fs.readFile(envLocalPath, "utf-8");
    else if (await fileExists(envPath)) localContent = await fs.readFile(envPath, "utf-8");
  } catch {}

  const definedVars = new Set(
    localContent
      .split("\n")
      .map((l) => l.trim().split("=")[0])
      .filter((k) => k.length > 0 && !k.startsWith("#"))
  );

  console.log(`\n${pc.bold("✦ Project Environment Variable Audit")}\n`);

  const table = createTable({ head: ["Variable Name", "Referenced In Code", "Status in Local .env"] });

  for (const v of varList) {
    const isSet = definedVars.has(v);
    table.push([
      pc.bold(v),
      pc.cyan("Yes"),
      isSet ? pc.green("✓ Configured") : pc.yellow("▲ Missing in .env.local"),
    ]);
  }

  console.log(table.toString());
  console.log();

  if (options.generateExample || varList.length > 0) {
    const examplePath = path.join(projectRoot, ".env.example");
    const exampleLines = [
      "# Generated by Push44 CLI",
      "# Copy to .env.local and fill in your keys",
      "",
      ...varList.map((v) => `${v}=your_${v.toLowerCase()}_here`),
      "",
    ];
    await fs.writeFile(examplePath, exampleLines.join("\n"), "utf-8");
    logger.success(`Generated template file: ${pc.cyan(examplePath)}`);
  }
}

async function fileExists(filePath: string): Promise<boolean> {
  try {
    await fs.access(filePath);
    return true;
  } catch {
    return false;
  }
}
